In [1]:
import pandas as pd
import numpy as np
import tweepy
import json
import matplotlib.pyplot as plt

In [2]:
from tweepy import OAuthHandler
 
consumer_key = 'OWea1JDj2RMgv9ktXcKkM3CRI'
consumer_secret = 'zolroSpEUpqFrTABaVHttXDYrKAIWBBGPpFjXZ5j4r201obVWq'
access_token = '927171157018759173-tqtWOcZMkWsnCvUToWsR3W0qSp64jwm'
access_secret = 'qMvXFuUpsnZD3b2TB1O49aGLSU6p607hDBnzkaYCdJWxR'
 
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
 
api = tweepy.API(auth)

In [3]:
# We import our access keys:
from credentials import *    # This will allow us to use the keys as variables

# API's setup:
def twitter_setup():
    """
    Utility function to setup the Twitter's API
    with our access keys provided.
    """
    # Authentication and access using keys:
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)

    # Return API with authentication:
    api = tweepy.API(auth)
    return api

In [37]:
MAX_TWEETS = 10000

data = pd.DataFrame(data=[tweet.text for tweet in tweepy.Cursor(api.search, q='#S&P500',lang = "en", rpp=100).items(MAX_TWEETS)], columns=['Tweets'])

TweepError: Twitter error response: status code = 429

In [ ]:
data['len']  = np.array([len(tweet.text) for tweet in tweepy.Cursor(api.search, q='#S&P500',lang = "en", rpp=100).items(MAX_TWEETS)])
data['User']   = np.array([tweet.user.screen_name for tweet in tweepy.Cursor(api.search, q='#S&P500',lang = "en", rpp=100).items(MAX_TWEETS)])

data['Date'] = np.array([tweet.created_at for tweet in tweepy.Cursor(api.search, q='#S&P500', lang = "en",rpp=100).items(MAX_TWEETS)])
data['Source'] = np.array([tweet.source for tweet in tweepy.Cursor(api.search, q='#S&P500',lang = "en", rpp=100).items(MAX_TWEETS)])
data['Likes']  = np.array([tweet.favorite_count for tweet in tweepy.Cursor(api.search, q='#S&P500',lang = "en", rpp=100).items(MAX_TWEETS)])
data['RTs']    = np.array([tweet.retweet_count for tweet in tweepy.Cursor(api.search, q='#S&P500',lang = "en", rpp=100).items(MAX_TWEETS)])

In [ ]:
data

In [30]:
tweet.user.screen_name

'realDonaldTrump'

In [4]:
extractor = api


# We create a tweet list as follows:
tweets = extractor.user_timeline(screen_name="realDonaldTrump", count=200)
print("Number of tweets extracted: {}.\n".format(len(tweets)))

# We print the most recent 5 tweets:
print("5 recent tweets:\n")
for tweet in tweets[:5]:
    print(tweet.text)
    print()

Number of tweets extracted: 200.

5 recent tweets:

Our Steel and Aluminum industries (and many others) have been decimated by decades of unfair trade and bad policy w… https://t.co/OEgFJVYtCs

Many ideas, some good &amp; some not so good, emerged from our bipartisan meeting on school safety yesterday at the Whi… https://t.co/aJ2m3fH3y3

It was an honor to welcome bipartisan members of Congress for a discussion on SAFE schools and SAFE communities. As… https://t.co/EPB1EN3HRc

Today we honor Billy Graham as only three private citizens before him have been honored.

We say a prayer for our… https://t.co/CbrnqFwUuZ

Starting at a small Bible School in Florida, Billy Graham soon led a nationwide revival. From a large tent in Los A… https://t.co/rhhuOssGmf

In [7]:
data.head()

,Tweets,len,ID,Date,Source,Likes,RTs
0,Our Steel and Aluminum industries (and many ot...,140,969183644756660224,2018-03-01 12:12:42,Twitter for iPhone,34116,7961
1,"Many ideas, some good &amp; some not so good, ...",144,969178931369783296,2018-03-01 11:53:58,Twitter for iPhone,32148,7516
2,It was an honor to welcome bipartisan members ...,140,968962582374621185,2018-02-28 21:34:16,Media Studio,40642,9346
3,Today we honor Billy Graham as only three priv...,139,968924154031497226,2018-02-28 19:01:34,Twitter for iPhone,56322,13852
4,"Starting at a small Bible School in Florida, B...",140,968917941671612416,2018-02-28 18:36:53,Twitter for iPhone,51597,11669

In [10]:
from textblob import TextBlob
import re

def clean_tweet(tweet):
    '''
    Utility function to clean the text in a tweet by removing 
    links and special characters using regex.
    '''
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())

def analize_sentiment(tweet):
    '''
    Utility function to classify the polarity of a tweet
    using textblob.
    '''
    analysis = TextBlob(clean_tweet(tweet))
    return analysis.sentiment.polarity

In [11]:
# We create a column with the result of the analysis:
data['SA'] = np.array([ analize_sentiment(tweet) for tweet in data['Tweets'] ])

# We display the updated dataframe with the new column:
display(data.head(10))

,Tweets,len,ID,Date,Source,Likes,RTs,SA
0,Our Steel and Aluminum industries (and many ot...,140,969183644756660224,2018-03-01 12:12:42,Twitter for iPhone,34116,7961,-0.233333
1,"Many ideas, some good &amp; some not so good, ...",144,969178931369783296,2018-03-01 11:53:58,Twitter for iPhone,32148,7516,0.633333
2,It was an honor to welcome bipartisan members ...,140,968962582374621185,2018-02-28 21:34:16,Media Studio,40642,9346,0.600000
3,Today we honor Billy Graham as only three priv...,139,968924154031497226,2018-02-28 19:01:34,Twitter for iPhone,56322,13852,0.000000
4,"Starting at a small Bible School in Florida, B...",140,968917941671612416,2018-02-28 18:36:53,Twitter for iPhone,51597,11669,-0.011905
5,"Today, in the center of this great Chamber lie...",140,968896168230051850,2018-02-28 17:10:22,Twitter for iPhone,61638,15174,0.350000
6,Why is A.G. Jeff Sessions asking the Inspector...,140,968856971075051521,2018-02-28 14:34:37,Twitter for iPhone,78203,22981,0.025000
7,45 year low on illegal border crossings this y...,140,968850364383596545,2018-02-28 14:08:21,Twitter for iPhone,97118,18688,0.100000
8,I have decided that sections of the Wall that ...,139,968825596133478400,2018-02-28 12:29:56,Twitter for iPhone,89949,20279,0.200000
9,The Heritage Foundation has just stated that 6...,140,968818810005450752,2018-02-28 12:02:58,Twitter for iPhone,84298,21405,0.000000